language: python
python: '3.5'
env:
  global:
  - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  - SEGFAULT_SIGNALS=all
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
before_install:
- python --version
- uname -a
- lsb_release -a
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
install:
- pip install tox
- virtualenv --version
- easy_install --version
- pip --version
- tox --version
cache:
  directories:
  - $HOME/.cache/pip
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
